accounts/urls.py
from django.urls import path
from django.urls import path, re_path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout,name='logout'),
    path('customer/',views.customer,name='customer'),
    path('editor/',views.editor,name='editor'),


    path('customer/add/', views.createCustomer, name='customer-add'),
    path('update_customer/<str:pk>/', views.updateCustomer, name="customer-update"),
    path('delete_customer/<str:pk>/', views.deleteCustomer, name="customer-delete"),
    # path('customer/add/', views.CustomerCreateView.as_view(), name='customer-add'),
    # path('customer/<int:pk>/', views.CustomerUpdateView.as_view(), name='customer-update'),
    # path('customer/<int:pk>/delete/', views.CustomerDeleteView.as_view(), name='customer-delete'),
    
    path('editor/add/', views.createEditor, name='editor-add'),
    path('update_editor/<str:pk>/', views.updateEditor, name="editor-update"),
    path('update_admin/<str:pk>/', views.updateAdmin, name="admin-update"),
    path('delete_editor/<str:pk>/', views.deleteEditor, name="editor-delete"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls.conf import  include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls',namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


# Create your models here.
class User(AbstractUser):

    email = models.EmailField('Email',unique=True)
    image = models.ImageField("Image 40x40 ",upload_to='profile_images',null=True)
    username = models.CharField('Username', max_length=50,unique=True)
    create = models.BooleanField(default=True)
    read = models.BooleanField(default=True)
    update = models.BooleanField(default=True)
    delete = models.BooleanField(default=True)


    USERNAME_FIELD= 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self) -> str:
        return self.username

    



class Customer(models.Model):
	name = models.CharField("Name",max_length=50)
	email = models.EmailField("Email",unique=True)
	phone = models.CharField('Phone',max_length=50)
	image = models.ImageField("Image", upload_to='customer_image')
	date_created = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self) -> str:
		return self.name

accounts/views.py
from django import http
from django.forms.forms import Form
from django.http.response import HttpResponse
from accounts.models import  Customer
from django.shortcuts import redirect, render
from .froms import ChangeEmail, CustomerForm, Login, UserForm
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from .decorators import allowed_users, unauthenticated_user,admin_only
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy 
from django.contrib.auth import get_user_model
User = get_user_model()
from django.utils.encoding import force_text 
from accounts.tasks import send_confirmation_mail 
from accounts.tools.tokens import account_activation_token 
from django.utils.http import urlsafe_base64_decode
from django.contrib import messages
# Create your views here.

@unauthenticated_user
def login(request):
    form = Login(data=request.POST)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username,password=password)
        if user:
            django_login(request,user)
            messages.success(request,'You logged in successfuly')
            return redirect(reverse_lazy('accounts:home'))
        else:
            messages.error(request,'The information you entered is valid')

    context = {
        'form':form
    }
    return render(request,'accounts/login.html',context)   


def logout(request):
    django_logout(request)
    return redirect(reverse_lazy('accounts:login'))



@login_required(login_url='accounts:login')
def home(request):
    return render(request, 'accounts/dashboard.html')


@login_required(login_url='accounts:login')
def customer(request):
    if request.user.read == True:

        customers= Customer.objects.all()
        context={
            'customers':customers

        }

        return render(request,'accounts/customer.html',context)
    else:
        return HttpResponse("<p>You are note permissions</p>")


@login_required(login_url='login')
# @allowed_users(allowed_roles=['admin'])
def createCustomer(request):
    form=CustomerForm()
    if request.user.create == True:
	    if request.method == 'POST':
		    form = CustomerForm(request.POST, request.FILES)
		    if form.is_valid():
			    form.save()
			    return redirect('/customer')
	    context = {'form':form}
	    return render(request, 'accounts/create.html', context)
    else:
        return HttpResponse("<p>You are note permissions</p>")

@login_required(login_url='login')  
def updateCustomer(request, pk):
    if request.user.update == True:

        customer = Customer.objects.get(id=pk)
        form = CustomerForm(instance=customer)
        if request.method == 'POST':
            form = CustomerForm(request.POST, request.FILES, instance=customer)
            if form.is_valid():
                form.save()
                return redirect('/customer')

        context = {'form':form}
        return render(request, 'accounts/create.html', context)
    else:
        return HttpResponse("<p>You are note permissions</p>")


@login_required(login_url='login')
def deleteCustomer(request, pk):
    if request.user.delete == True:
        customer = Customer.objects.get(id=pk)
        if request.method == "POST":
            customer.delete()
            return redirect('/customer')
        return render(request, 'accounts/delete.html')
    else:
        return HttpResponse("<p>You are note permissions</p>")


# editor
@login_required(login_url='accounts:login')
def editor(request):
    editors= User.objects.filter(is_superuser = False).all
    context={
        'editors':editors
    }
    return render(request,'accounts/editor.html',context)


@login_required(login_url='login')
def createEditor(request):
    form=UserForm()
    if request.user.is_superuser == True:
	    form=UserForm()
	    if request.method == 'POST':
		    form = UserForm(request.POST)
		    if form.is_valid():
			    form.save()
			    return redirect('/editor')
	    context = {'form':form}
	    return render(request, 'accounts/create.html', context)

@login_required(login_url='login')
def updateEditor(request, pk):
    if request.user.is_superuser == True:

        editor = User.objects.get(id=pk)
        form = UserForm(instance=editor)
        if request.method == 'POST':
            form = UserForm(request.POST,request.FILES, instance=editor)
            if form.is_valid():
                form.save()
                return redirect('/editor')

        context = {'form':form}
        return render(request, 'accounts/create.html', context)


@login_required(login_url='login')
def deleteEditor(request, pk):
    if request.user.is_superuser == True:
        editor = User.objects.get(id=pk)
        if request.method == "POST":
            editor.delete()
            return redirect('/editor')
        return render(request, 'accounts/delete.html')


@login_required(login_url='login')
def updateAdmin(request,pk):

    user = User.objects.get(id=pk)
    form = UserForm(instance =user)
    if request.method == 'POST':
        form = UserForm(request.POST,instance = user)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {
        'form':form,
    }
    return render(request, 'accounts/create.html', context)

accounts/templates/accounts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Dashboard</title>
  </head>
  <body>
    {% include 'accounts/includes/navbar.html' %}
    {% block content %}
    
        
    {% endblock %}

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>

accounts/templates/accounts/create.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags  %}
{% block content %}
<div class="container" style="margin-top: 50px;">
    <div class="row">
        <div class="col-sm-12" >
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field|as_crispy_field}}
                </div>
                
                {% endfor %}
                
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/customer.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags  %}
{% block content %}
    <div class="container" style="margin-top: 20px;">
        <div class="row">
            <div class="col-sm-12">
              <h2>Customer List</h2>
                <table class="table table-dark">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for customer in customers %}
                      <tr>
                        <th scope="row">{{customer.id}}</th>
                        <td>{{customer.name}}</td>
                        <td>{{customer.email}}</td>
                        <td><a href="{% url 'accounts:customer-update' customer.pk %}"><i class="fas fa-edit"></i>Update</a></td>
                        <td><a href="{% url 'accounts:customer-delete' customer.pk %}" onclick="return confirm('Are you sure to delete?')"><i class="fas fa-trash-alt"></i>Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-sm-12">
            
            {% if request.user.is_superuser %}
            <h2>Your profile</h2>
            <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Username</th>
                    <th scope="col">Email</th>
                    <th scope="col">Create</th>
                    <th scope="col">Read</th>
                    <th scope="col">Update</th>
                    <th scope="col">Delete</th>
                    
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">{{request.user.id}}</th>
                    <td>{{request.user.username}}</td>
                    <td>{{request.user.email}}</td>
                    <td>{{request.user.create}}</td>
                    <td>{{request.user.read}}</td>
                    <td>{{request.user.update}}</td>
                    <td>{{request.user.delete}}</td>
                    <td><a href="{% url 'accounts:admin-update' request.user.pk %}"><i class="fas fa-edit"></i>Update</a></td>
                  </tr>  
                </tbody>
              </table>
              {% endif %}
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/delete.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags  %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Do you want to delete?</h1>
                
                <input type="submit" value="YES">
            </form>
        </div>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/editor.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags  %}
{% block content %}
    <div class="container" style="margin-top: 20px;">
        <div class="row">
            <div class="col-sm-12">
                <h2>Editor List</h2>
                <table class="table table-dark">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Create</th>
                        <th scope="col">Read</th>
                        <th scope="col">Update</th>
                        <th scope="col">Delete</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                        {% for editor in editors %}
                      <tr>
                        <th scope="row">{{editor.id}}</th>
                        <td>{{editor.username}}</td>
                        <td>{{editor.email}}</td>
                        <td>{{editor.create}}</td>
                        <td>{{editor.read}}</td>
                        <td>{{editor.update}}</td>
                        <td>{{editor.delete}}</td>
                        <td><a href="{% url 'accounts:editor-update' editor.pk %}"><i class="fas fa-edit"></i>Update</a></td>
                        <td><a href="{% url 'accounts:editor-delete' editor.pk %}" onclick="return confirm('Are you sure to delete?')"><i class="fas fa-trash-alt"></i>Delete</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Customer
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:customer' %}">List</a>
            <a class="dropdown-item" href="{% url 'accounts:customer-add' %}">Add</a>
          </div>
      
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Editor
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:editor' %}">List</a>
            <a class="dropdown-item" href="{% url 'accounts:editor-add' %}">Add</a>
          </div>
          
        </li>
        {% endif %}
        
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href=""> Hello,{{user.username}}</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}
        
      </ul>
      
    </div>
  </nav>

accounts/templates/accounts/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Dashboard</title>
  </head>
  <body>
    {% load crispy_forms_tags  %}
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}} " {% endif %} style="text-align: center;margin-top: 50px;">{{message}}</div>
    {% endfor %}
    {% endif %}
    
    <div class="continer">
        <div class="row justify-content-center mt-5">
            <div class="col-sm-6">
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                <div class="form-group">
                    {{ field|as_crispy_field}}
                </div>
                
                {% endfor %}
                
                <input type="submit" value="Submit" class="btn btn-primary">
                </form>
              
            </div>
        </div>
    </div>
        
    

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </body>
</html>